-- Create database and schemas
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS DE_DEMO_ROLE;
CREATE DATABASE IF NOT EXISTS call_centre_analytics_db;
-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS cca_xs_wh 
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

USE DATABASE call_centre_analytics_db;
USE SCHEMA PUBLIC;

-- GRANT OWNERSHIP ON THE DB TO THE CUSTOM ROLE
GRANT OWNERSHIP ON DATABASE call_centre_analytics_db TO ROLE DE_DEMO_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE call_centre_analytics_db TO ROLE DE_DEMO_ROLE COPY CURRENT GRANTS;

GRANT USAGE ON WAREHOUSE cca_xs_wh TO ROLE DE_DEMO_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE DE_DEMO_ROLE;

-- Update the username 
GRANT ROLE DE_DEMO_ROLE TO USER <username>; 

USE ROLE DE_DEMO_ROLE;
USE DATABASE call_centre_analytics_db;
USE WAREHOUSE cca_xs_wh;
USE SCHEMA PUBLIC;

CREATE STAGE IF NOT EXISTS UDF
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
DIRECTORY = (ENABLE = TRUE)
COMMENT = ' used to create UDFs';
CREATE STAGE IF NOT EXISTS AUDIO_FILES
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
DIRECTORY = (ENABLE = TRUE)
COMMENT = ' stage for Cortex Analyst semantic model files';;;

CREATE STAGE IF NOT EXISTS SEMANTIC_MODEL_STAGE
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
DIRECTORY = (ENABLE = TRUE)
COMMENT = ' stores the semantic yaml file for cortex analyst';



-- Stored the audio file path and the transcription of the audio file. Duration is in seconds.
 CREATE or REPLACE TABLE ALL_CLAIMS_RAW (
	DATETIME DATE,
	AUDIOFILE VARCHAR(16777216),
    AUDIOFILE_RELATIVE_PATH VARCHAR(16777216),
	CONVERSATION VARCHAR(16777216),
	PRESIGNED_URL_PATH VARCHAR(16777216),
	DURATION FLOAT  NULL);

 CREATE or REPLACE TABLE AUDIO_CLAIMS_EXTRACTED_INFO 
    (
        DATETIME DATE,
        AUDIO_FILE_NAME VARCHAR(100),
        AUDIO_FULL_FILE_PATH VARCHAR(16777216),
        RAW_CONVERSATION VARCHAR(16777216),
        PROMPTED_CONVERSATION VARCHAR(16777216),
        DURATION FLOAT,
        CALL_DETAILS VARIANT,
        CALL_SUMMARY VARCHAR(16777216),
        CALL_SENTIMENT variant,
        REPONSE_GIVEN FLOAT
    );


